# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rubygems'
require 'bundler/setup'
require 'the_city_auth'
require 'yaml'
require 'openssl'
require 'base64'
require 'cgi'

$auth = {
  :secret_key => '123456789abcdef0123456789abcdef012345678',
  :user_token => '123456789abcdef0'
}

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  #config.filter_run :focus

  config.mock_with :nothing
end
